apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml
- certificate.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:0f2dc8c6c5f4079f6936a92bb3e899b53b69487d927b5c9f431f070bed3dc95e
  name: ghcr.io/pablitxn/garage-sale:prod
  newName: ghcr.io/pablitxn/garage-sale
