apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml
- certificate.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:8ca834d3521ec1bce12a1e6f8e1e7ed2d7a22eda6cbf7c5567b4e6354a9c6892
  name: ghcr.io/pablitxn/garage-sale:prod
  newName: ghcr.io/pablitxn/garage-sale
