apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml
- certificate.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:274c6a177e77ac55b38e46dc6a999d49b41944570d537d74c7949b5028e71401
  name: ghcr.io/pablitxn/garage-sale:prod
  newName: ghcr.io/pablitxn/garage-sale
