apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml
- certificate.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:04fba8ac23bacc216f085876747324decc0025d1eb547654ec426bc353dc9a88
  name: ghcr.io/pablitxn/garage-sale:prod
  newName: ghcr.io/pablitxn/garage-sale
